"""Original Interface Report front-page series, published 25 September 2026.

Source URLs point to primary announcements or the publisher's own websites.
The arguments in the articles are Interface Report analysis, not source claims.
"""
ARTICLES = [
{
'slug':'oleh-hebel-three-brand-product-system','title':'One Founder, Three Brands: A Product System in Public','seo':'A three-brand product system by Oleh Hebel','dek':'How SuperPrompt, Interface Report and Ship Index Grow show three different jobs connected by one product-thinking method.','category':'Design & UX','image':'patterns.png','image_alt':'Three distinct brand identities organized around shared product principles','kind':'Founder portfolio analysis','source_url':'https://superprompt.pro/','source_name':'Oleh Hebel & Co · SuperPrompt','extra_sources':[('Interface Report','https://interfacereport.com/'),('Ship Index Grow','https://shipindexgrow.top/'),('Oleh Hebel on LinkedIn','https://www.linkedin.com/in/olehhebel/')],
'intro':"A consultancy, a publication and a school can look like unrelated bets. Read together, Oleh Hebel & Co at SuperPrompt, Interface Report and Ship Index Grow form a more useful picture: one founder using distinct brands for distinct customer jobs. This is an analysis of the public products, not a claim that the organizations share a single codebase or that any particular internal workflow has been independently audited. The interesting achievement is not merely launching three sites. It is giving each a reason to exist, a recognizable voice and a clear next action while retaining a coherent view of product quality.",
'sections':[
('Start with the job, then choose the identity',"SuperPrompt presents fixed-scope design and UX work: bring an uneven product, agree on the smallest useful fix, ship a coherent flow. Interface Report serves a different reader moment: understand what is happening across AI products, agents and design before making a decision. Ship Index Grow turns the same practical concern into a six-week learning path, from idea and product through launch, indexing and growth. These promises should not be collapsed into one generic services homepage. Each site gives a visitor a different answer to the question, ‘What can I do here?’","The three experiences share a belief that making a demo fast is not enough. A product should explain itself, earn trust and hold up after launch. That principle can be reused even when visual identity changes. A blue editorial accent can signal a publication, while a teaching experience needs progress and sequence. Reusing the underlying decision rules is valuable; making every screen look alike would obscure the offer."),
('A visible system is stronger than a slogan',"On SuperPrompt, the constraint is a scoped sprint: a problem, a working flow and a handoff. Interface Report practices explanation through sourced analysis and separated editorial and commercial pages. Ship Index Grow organizes learning around a real launched product rather than a rotating list of tools. These are observable distinctions on the live sites. We cannot verify audience outcomes, enrollment or conversion from their homepages alone, and we should not claim that they are proven by the existence of the sites.","The shared architecture is still instructive. State the user’s starting point, show the transformation, explain the proof the visitor can inspect, then give one relevant call to action. Repeat those principles at different levels of the journey. A founder can use a publication to make sense of an issue, a design practice to fix a product, and a school to learn how to repeat the process. The transitions should be disclosed and chosen by the visitor, not hidden in an editorial recommendation."),
('Keep editorial independence legible',"The publisher of Interface Report also operates SuperPrompt and Ship Index Grow. That relationship matters when the publication discusses its own ecosystem. Readers need to know whose work is being described and which links lead to a founder-owned service. This article makes that relationship explicit. The case study is a first-party portfolio interpretation; it is not an independent endorsement of a client, and no unverified performance numbers are offered.","Editorial and commercial boundaries are part of the experience design. An independent analysis of a company should not become a covert advertisement because the founder can also sell design work. A clearly marked portfolio essay can admire the craft while allowing readers to inspect the sites and disagree. The better claim is specific: the offers, paths and content systems are visibly differentiated and connected by a product method. The weaker claim would be that the method has already won a market."),
('What another founder can borrow',"Map the jobs before naming the brands. Write one sentence for the visitor’s problem, the promised outcome and the evidence each property can show. Then design shared elements that reduce maintenance—accessibility rules, content structure, measurement conventions and component behavior—without cloning the visual voice. Finally, draw an honest map of where one property links to another. If every path ends in the same sales funnel, the brands are decoration; if each performs a distinct job, the portfolio begins to act like a system.","Oleh’s work deserves attention because the three public properties make that reasoning tangible. SuperPrompt shows service packaging, Interface Report shows an editorial product, and Ship Index Grow shows a structured learning journey. The strongest next proof would be longitudinal: completed projects, published analysis readers return to, and pilot outcomes from the school. Until then the sites are useful, inspectable artifacts of product thinking in progress, which is already a more concrete story than a vague ‘multibrand strategy’ slide."),
('A direct reading of the portfolio',"Explore the three live sites in order of the problem you have now, not in the order a founder launched them. Need a product critique or a contained design sprint? Start with SuperPrompt. Need a sourced account of a new interface or an agent pattern? Read Interface Report. Need a guided path from idea to an indexed product? Examine Ship Index Grow’s published program. The same person can plausibly serve all three moments only when the boundaries and deliverables remain plain.","The practical lesson is that multiple brands are a promise to manage multiple expectations. That requires stronger editorial labels, sharper product positioning and clear ownership, not simply more logos. You can follow Oleh Hebel’s public work on LinkedIn and judge the system from its published output. This article states an interpretation of what is visible in September 2026; it does not imply private access to his roadmap or first-hand interview testimony.")],
'questions':['Can a visitor name the distinct job of each site in ten seconds?','Are founder-owned links and editorial opinions clearly separated?','What public outcome would prove this portfolio helps real users?']
},
{
'slug':'coinbase-code-connect-agent-design-system','title':'Agents Need Component Contracts, Not Screenshot Guesswork','seo':'Coinbase Code Connect: agents and design systems','dek':'Coinbase’s Code Connect test reframes design systems as executable context for coding agents.','category':'Design & UX','image':'patterns.png','image_alt':'Design component contracts linking interface design to production code','kind':'Case study analysis','source_url':'https://www.figma.com/blog/how-coinbase-used-code-connect-to-shrink-token-costs/','source_name':'Figma · Coinbase Code Connect case study',
'intro':"Figma’s September 2 account of Coinbase’s design system reports improved adherence to its components and an average 22.5% reduction in token costs in the team’s Code Connect experiment. The interesting point is not that a tool saved tokens in one test. It is that an agent with explicit links from design components to code has fewer opportunities to invent a parallel interface. This is a vendor-published case study, so treat the number as a reported result in that setting, not a universal benchmark for every team or model.",
'sections':[
('Where the ambiguity enters',"A visual design gives an agent shape, spacing and labels but often hides the implementation contract. Which component is approved? What props are legal? Is the color token semantic or a literal value? Which interaction states exist off canvas? Without answers, the agent writes plausible code that looks right in a screenshot and drifts from the system in production. Human engineers can infer unwritten conventions from a repository; agents need those conventions made legible and retrievable.","Code Connect is one way to narrow that gap. The reported Coinbase setup links Figma components to their code siblings. That matters because the agent can work from a mapping rather than guessing a replacement. It does not automatically guarantee accessible states, correct behavior or a good product decision. It reduces one kind of uncertainty: where a component comes from and how the design language is represented in code."),
('Measure adherence separately from speed',"A team tempted by the reported token reduction should first ask what changed in its own output. Did the agent use the approved component rather than a hand-rolled substitute? Did it preserve hover, keyboard focus, errors and loading? Did the resulting pull request require fewer rounds of correction? Token cost is useful, but it is only one cost in a delivery system. A cheaper wrong screen remains expensive after review and rework.","Create a small evaluation set of known interface tasks. Run it with and without component mappings, using the same repository, task descriptions and review criteria. Score implementation against actual component imports, semantic token use, accessibility checks and final diff size. Record how much human editing was needed. A narrow experiment can show whether the mapping helps your stack without pretending Coinbase’s conditions match yours."),
('The new maintenance work',"A design-to-code contract becomes another artifact that can become stale. When the design library changes but production props do not, an agent can confidently follow the wrong mapping. Ownership matters: decide who updates links, who reviews mismatches and how a deprecated component is surfaced. A useful system should make the current component path visible inside the developer workflow, not demand that every engineer remember a separate design archive.","The team should also guard against a subtler failure: component obedience without product judgment. Agents can follow the library perfectly while implementing a confusing journey. A component contract answers how to build a known pattern; it does not answer whether that pattern is right for the user’s task. Keep product review and user research in the loop."),
('A practical rollout',"Start with a handful of high-volume components: buttons, input fields, dialogs, navigation and status messages. Include examples for disabled, loading, validation and empty states; name the variants in terms a developer and an agent will encounter. Connect each design component to the real code implementation. Then ask an agent to assemble a modest flow, inspect the result and record every ambiguous instruction it encountered.","Treat those ambiguities as backlog items for the design system. If a model repeatedly builds a custom dialog, perhaps the approved dialog is poorly documented or difficult to discover. The same observation helps human engineers. The agent is a diagnostic probe, not the owner of the system. Coinbase’s report is compelling precisely because the design system is being tested as working infrastructure rather than admired as a static gallery."),
('What this signals for teams',"Design systems now have at least two audiences: people who inspect examples and machines that need explicit, testable boundaries. Both benefit from precise names, supported variants and a reliable bridge into code. The business case is not ‘AI will design everything’; it is that fewer hidden assumptions mean less drift during implementation.","Read the Figma case study for its setup and reported result, then establish a baseline in your own repository. Keep the claim modest. A mapped library can improve consistency for the tasks it covers. It cannot replace evidence about comprehension, performance or accessibility in the finished experience. The most mature team will publish its own numbers alongside the conditions under which they were measured.")],
'questions':['Can the agent find the production component for every common design element?','How often does it generate custom substitutes?','Which review failures remain even after mappings are supplied?']
},
{
'slug':'microsoft-ai-work-system-costs','title':'The AI Work System Has Two Ledgers','seo':'Microsoft AI at work: subscriptions and agent usage','dek':'Microsoft’s September AI-at-work framing separates seats from usage. Product teams should separate control from consumption too.','category':'AI Products','image':'agent-control-surface.png','image_alt':'Two layers of AI work: human access and metered agent execution','kind':'Product analysis','source_url':'https://www.microsoft.com/en-us/copilot/blog/2026/09/23/building-the-system-for-ai-at-work/','source_name':'Microsoft · Building the system for AI at work',
'intro':"Microsoft’s September 23 description of AI at work distinguishes a predictable user subscription from usage billing for agent work that can vary greatly in duration and complexity. This is a vendor’s business-model account, not a neutral finding that every customer should adopt its pricing. It raises a practical design question: can the person commissioning a job see what they have access to, what work the agent may perform, how the cost is metered and when to stop it? A clean chat box is insufficient when the unit of work is no longer one conversation.",
'sections':[
('Seats and work are different objects',"A seat tells you who can use a product. A usage meter tells you what execution has consumed. When the two appear in one vague ‘AI included’ label, teams struggle to predict spend. A user may trigger a short summary or a multi-hour research process from the same surface. An administrator needs a budget and a worker needs a meaningful estimate before a job starts. Those are separate user experiences, even if the billing system combines them later.","The design response is to model a job explicitly. Show its owner, purpose, estimated range, current state, connected systems and cancellation path. Show the difference between a permission to start jobs and a quota for work already underway. Users should not have to inspect a financial dashboard to discover that a supposedly passive assistant has been consuming resources overnight."),
('Turn cost visibility into interaction design',"Cost feedback should arrive at the decision point. Before a large run, explain what the agent will do and what could make the work longer. During execution, display progress in units that help a person decide whether to continue. Afterward, attach the spend to an outcome: a report produced, records changed or a task completed. A raw token counter rarely tells a business owner whether the work was worthwhile.","A sensible product can offer stop conditions: maximum spend, maximum duration, required approval before external actions, or an escalation when the plan changes. The exact thresholds depend on the organization; the invariant is agency. If limits exist only in an admin console, the individual starting the work may still misunderstand what is happening. Good cost UX gives administrators policy and workers timely context."),
('Evaluation has its own ledger',"Microsoft also describes continuous improvement loops for agents. That claim invites a separate measurement question: which tasks improved, against what baseline, and at what total cost? Teams should record task success and human correction time alongside bills. A cheap agent that sends incomplete work downstream can be more costly than a more expensive one that resolves the task reliably.","Construct an evaluation ledger with a small set of representative jobs. For each, note expected output, risk level, allowed tools, human acceptance criteria and actual spend. Review failures as product issues, not only model issues. Sometimes the prompt is vague; sometimes the underlying data is stale; sometimes the interface implied the job had authority it did not possess. A single model benchmark will not uncover those differences."),
('A product team’s decision',"When considering a platform, ask whether price controls apply before or after a job starts, whether active work can be stopped, and whether administrators can attribute use to meaningful business outcomes. Look for a clear distinction between included access and metered execution. Ask whether credits expire, whether the meter is observable, and whether people can inspect the actions for which they were charged. These are product questions as much as procurement questions.","The broader shift is from selling AI as an always-available conversation to selling measurable work. That changes onboarding, permission design, usage analytics and trust. Microsoft’s post is one articulation of the shift; another vendor might meter differently. The principle holds across models: users need to understand both what they can ask the system to do and what it costs when the system acts."),
('What to watch next',"Do not take a headline about agent productivity as proof of return on investment. Look for published definitions of success, a credible comparison and the operational costs of supervision. A product that exposes budgets but hides failure patterns is still difficult to manage. A product that exposes beautiful job histories but cannot set spend ceilings is difficult to trust.","The most useful next experiment is a bounded workflow in your organization. Set a budget, define one outcome and compare agent work with the current human process. Document the handoffs, corrections and customer effects. Then decide whether the seat, the usage meter or both belong in the experience. The answer should follow the work, not a platform’s preferred pricing narrative." )],
'questions':['Can a worker see an estimate before a long-running task?','Can an administrator stop or cap work in progress?','Is measured value tied to accepted outcomes rather than activity?']
},
{
'slug':'zendesk-specialized-agents-service-design','title':'Specialized Agents Make Service Policy a UX Surface','seo':'Zendesk Specialized Agents and service UX','dek':'Zendesk’s new agent categories move service automation closer to business rules, handoffs and visible accountability.','category':'Human–AI','image':'trust.png','image_alt':'Customer service workflow showing specialist agent decisions and handoffs','kind':'Product analysis','source_url':'https://www.zendesk.com/newsroom/articles/specialized-agents/','source_name':'Zendesk · Specialized Agents announcement',
'intro':"Zendesk’s September announcement describes Industry Agents for common sector tasks and Custom Agents for workflows unique to a business. The company says administrators can define a job, its systems, actions and points of human approval. That is a more concrete design brief than ‘put a bot on support’. The question for a service team is whether the automated worker can act within a real policy, explain its decisions and hand over a case without forcing the customer to repeat everything.",
'sections':[
('Specialization changes the unit of design',"A generic assistant can answer a question about an order. A service agent may also inspect its status, check a returns policy, calculate eligibility, issue a refund and record the result. Each step has a different consequence. The interface must expose the difference between information, recommendation and irreversible action. It should show which policy or record drove the decision and offer a human route when the customer disputes the outcome.","Zendesk names commerce integrations and industry workflows in its announcement, but an integration list does not guarantee good customer service. The decisive experience occurs at exceptions: mixed orders, partial refunds, damaged items and identity checks. A specialist agent succeeds when it knows both the ordinary path and when that path no longer applies. Designers should study exceptions before drawing the happy-path chat flow."),
('Policy is part of the product',"A refund policy is usually written for employees. An agent turns it into an executable constraint, so ambiguity suddenly becomes visible. Which exceptions are automatic? Who approves a high-value case? What evidence must be logged? If those questions remain unowned, the agent may be precise about a bad rule or inconsistent about a good one. Product design must include the policy editor, review queue and audit history, not just the customer-facing conversation.","Customers also need a comprehensible explanation. ‘The system cannot do that’ is not a service answer. A better response identifies the relevant condition, the next available action and how to reach someone who can review an exceptional case. The explanation should avoid revealing sensitive internal scoring or fraud controls while giving enough context to avoid an opaque rejection."),
('Handoff quality is the quiet metric',"A human escalation is not a failure if it prevents an incorrect action. Measure whether the human receives a concise account of what the customer asked, what the agent checked, what was already promised and where uncertainty remains. If the customer must restate the entire case, the apparent automation rate hides a poor service experience. Time saved by the first agent may simply move to the next person.","Construct test cases around ambiguous evidence and policy boundaries, not only routine successes. In a returns workflow, vary purchase date, item condition, order history and refund route. Verify that the agent asks only necessary questions, cites relevant records internally and records a reason for handoff. Track correction rates and customer effort alongside resolution. A high automated-resolution figure should never be read in isolation."),
('Keep vendor claims in their lane',"Zendesk reports execution volume and some customer outcomes in its announcement. Those figures are vendor-reported examples, not a comparative trial of all service agents. They establish that organizations are using the product; they do not establish the quality of every decision or the distribution of outcomes across industries. A buyer should ask for a test in its own policy environment and a way to inspect misclassifications.","The important shift is architectural: service knowledge becomes structured enough for an agent to apply and a person to review. That opens the possibility of more consistent service, but only if the human organization maintains the knowledge. A stale policy, a missing integration or a silent approval bypass is a product failure regardless of how fluent the agent sounds."),
('A practical pilot',"Pick one contained service request with clear outcomes and an existing human escalation route. Define the actions the agent may perform, the records it may read, and the conditions that require approval. Observe real customer language before writing the system’s prompts. Launch to a small audience and inspect every correction, not just the successful transcripts.","If the pilot works, the next task is maintenance: who updates rules when the business changes, and how do affected cases get re-evaluated? A specialist is useful because it stays close to a job. It becomes dangerous when a polished interface makes old assumptions look authoritative. Good service UX makes both competence and limits visible." )],
'questions':['Can the customer tell when the agent is informing versus acting?','Can a reviewer reconstruct why a decision was made?','Does a human handoff preserve context and avoid repeated questions?']
},
{
'slug':'uipath-cartographer-map-of-work','title':'Before Agents Automate Work, Map the Exceptions','seo':'UiPath Cartographer: a map of work for agents','dek':'UiPath Cartographer puts process knowledge, rules and exceptions into a living artifact. The UX challenge is keeping it true.','category':'AI Agents','image':'patterns.png','image_alt':'A map of operational steps, exceptions and owners for AI agents','kind':'Product analysis','source_url':'https://www.uipath.com/newsroom/uipath-launches-uipath-cartographer-map-of-work','source_name':'UiPath · Cartographer announcement',
'intro':"UiPath announced Cartographer on September 23 as a way to create a governed Map of Work from the scattered documents, rules and exceptions that define a process. The company says a named owner approves changes to that map. This is a sensible response to a recurring failure in automation: an agent can execute a documented step while missing the tacit judgment that makes the work correct. A map is useful only if it captures exceptions and remains close enough to reality for people to trust it.",
'sections':[
('The process diagram is usually the easy part',"Teams can list the visible stages of an invoice or a support case in an afternoon. What takes longer is finding the side paths: the customer whose contract has an override, the missing field an expert infers, the escalation triggered by a particular jurisdiction. Those exceptions are often buried in messages or held by a few experienced people. The automation risk is not merely that an agent cannot read them. It is that nobody realizes they are absent from the map until the agent acts.","Cartographer’s announcement argues for a living artifact assembled with guided conversation and context from existing systems. That is a product promise, not proof that every organization’s rules can be extracted completely. A responsible team should treat the generated map as a draft for subject-matter review. Mark uncertain steps, attach evidence and record which human owner accepted each rule."),
('Governance is a design problem',"If a process map becomes the authority for agents, changes to it become consequential. The system must show what changed, who proposed it, which cases are affected and how to roll back a mistaken update. A single ‘approved’ badge is too coarse for a map with many branches. Prefer step-level ownership and a readable change history. Users should be able to ask why a route was chosen and find the answer without reconstructing a hidden conversation.","A process owner should see both canonical rules and observed deviations. Sometimes a deviation is a mistake to fix; sometimes it is the only way work gets done because the documented policy is obsolete. An agent that blindly enforces either side may cause harm. The interface needs a place to resolve that disagreement before automating it at scale."),
('Test the map against real cases',"Build a sample of ordinary and exceptional cases from the recent past, with permission to use them for evaluation. Have staff trace how each case was actually handled, then ask the map to predict the route and required evidence. Count missing branches, conflicting instructions and unclear approvals. The goal is not a polished diagram; it is coverage of the conditions that change decisions.","When an agent executes work, keep a case-level trace linking the input, the selected path, the rule version and the final action. Reviewers should see where the agent followed the map and where it improvised. That distinction helps fix the underlying knowledge rather than endlessly patching prompts. It also makes a future human escalation far more efficient."),
('A map can become stale on day two',"Operational knowledge changes with new products, policies and organizational responsibilities. A useful map needs triggers for review: repeated overrides, rising exception volume, a new integration or a policy revision. Assign an owner and a cadence to each high-risk section. Without this loop, ‘single source of truth’ becomes a confident label on an old document.","UiPath’s customer-owned framing is important because ownership determines who can correct the model. Ask whether the map can be inspected, exported, versioned and compared with actual outcomes. Ask how data from sensitive systems is protected and which parts are safe for an agent to use. Those questions are more concrete than a demo showing the map created in minutes."),
('A useful adoption order',"Start with a process where mistakes are recoverable and experts are available for review. Capture the current route, collect exceptions, test historical cases and only then allow a limited agent to act. Measure the rate of human correction and the time required to update the map. Expand the scope when those numbers improve, not when the diagram looks complete.","The idea behind Cartographer is timely: as agents become better at operating software, the bottleneck moves to understanding the work. An organization that makes its real rules legible to people first gives machines a safer starting point. A map is not the destination; it is the interface between institutional memory and controlled action." )],
'questions':['Who can approve or roll back a process-rule change?','Which exceptions are missing from the current map?','Can every agent action be traced to a rule version?']
},
{
'slug':'rabbit-os3-agent-operating-system','title':'Rabbit OS3 Turns the Device into an Agent Boundary','seo':'Rabbit OS3: agentic operating system UX','dek':'Rabbit OS3 promises action across devices. The harder interface question is how users see authority, context and interruption.','category':'Human–AI','image':'agent-control-surface.png','image_alt':'An AI agent coordinating actions across connected devices','kind':'Product analysis','source_url':'https://www.rabbit.tech/newsroom/rabbitos-3-launch','source_name':'rabbit · OS3 announcement',
'intro':"Rabbit announced the general release of OS3 on September 22, describing an outcome-based assistant that can work through a web portal, messages and connected devices. It says a local agent can operate desktop software and files while connected model providers process relevant task context under their own terms. Those are product claims from the company’s announcement, not an independent privacy audit. The design question is concrete: when a single assistant can cross devices and act on a person’s behalf, where does the user see what it can access, what it has done and how to stop it?",
'sections':[
('One entry point hides many powers',"A single conversational entry point can reduce tool selection. A user says what they want instead of choosing between browser automation, code execution and a document workflow. But those capabilities have different risks and levels of reversibility. A search query is not the same as editing a local file, sending a message or purchasing an item. An outcome-first interface needs a way to reveal the action plan without requiring a person to learn every technical primitive.","The key moment is before an agent crosses an authority boundary. State which device and account it will use, what data it needs, what change it proposes and whether the action can be reversed. A persistent task view should remain available after the conversation scrolls away. The chat can be the entry point; the audit trail and controls must live somewhere stable."),
('Context portability is not data invisibility',"OS3’s announcement describes model flexibility and the ability to change models without losing context, memory or skills. That is appealing because users do not want to rebuild a working setup after switching providers. But portability creates questions: which data remains with the OS3 service, which information travels to the model provider, and what should be removed when a connection ends? The company describes some of these flows, including handling through its own servers before model handoff. Readers should inspect the current product terms for their chosen provider.","A useful interface should distinguish local file presence, extracted context, stored conversation and remembered preferences. ‘Your files stay local’ does not answer every question about snippets sent for inference. A user may accept a specific transfer for a task while rejecting persistent memory. Those decisions should be separate controls with concrete previews, not one broad trust toggle."),
('The interruption test',"An agentic OS earns trust when the user can pause, inspect and recover. Imagine a task that edits three files, waits for a web response and then prepares a message. Can the user stop after the second edit and see the exact state? Can the system resume without repeating an external action? Does it ask again when the destination or cost changes? Those details decide whether an agent feels helpful or unpredictable.","Design task states around real consequences: planned, awaiting approval, running, blocked, partially complete, completed and reverted where possible. Each state should have a next action in plain language. A decorative progress bar is less useful than a list of actual changes and pending permissions. Multi-device products especially need a single source of task truth when the user moves from phone to desktop."),
('How to evaluate the promise',"Run a bounded task with connected apps that contain only low-risk test data. Record every request for permission, what was sent to the provider, what the agent changed and what a human had to correct. Disconnect midway and reconnect on another device. Check whether the task history is coherent and whether any work happens twice. These observations are more informative than a polished launch demonstration.","Also test a refusal. A person should be able to say ‘do not touch this folder’ or ‘draft but never send’ and have that preference honored visibly. If the system cannot explain the boundary it is respecting, the user has to trust an invisible promise. This is not a claim that OS3 fails those tests; it is a product checklist prompted by the breadth of the announcement."),
('The category that emerges',"Rabbit’s release suggests an operating layer that connects intent with many device-level capabilities. The strategic advantage may be less about the model and more about continuity: a remembered task, clear authorization and reliable execution across surfaces. The corresponding liability is also continuity: a mistaken instruction or excessive permission can follow the user everywhere.","The product teams watching this category should study recovery as carefully as creation. More autonomy makes transparent limits more valuable. The best interface will make a powerful agent feel interruptible, inspectable and accountable, even when the execution crosses applications the user never opened directly." )],
'questions':['Can a user see every device and account a task will touch?','What task state survives a model or device switch?','Can a partially completed action be stopped and reviewed safely?']
},
{
'slug':'persistent-agent-interface-identity-routines','title':'Persistent Agents Need an Identity That Explains Work','seo':'Persistent agent UX: identity, memory and routines','dek':'xAI’s Grok Bot design notes offer a lens on persistent agents: fewer visible primitives, stronger expectations around memory.','category':'Design & UX','image':'trust.png','image_alt':'Persistent AI agent interface with clear routines, tools and artifacts','kind':'Design analysis','source_url':'https://x.ai/news/designing-grok-bot','source_name':'xAI · Designing Grok Bot',
'intro':"xAI’s September design account for Grok Bot describes a persistent agent with identity, memory, runtime and tools. Its authors narrow a growing vocabulary of chats, skills, connectors and sandboxes into five user-facing concepts: Bots, Chats, Prompts, Tools and Artifacts. The article is a first-party account of design choices, not a measured comparison with other interfaces. Its useful question is broader: what must remain visible when an AI system continues to act after one conversation ends?",
'sections':[
('Persistence changes the user’s mental model',"A chat session has a natural ending. A persistent agent may retain instructions, schedule work and revisit documents days later. That continuity can save setup, but it also changes the meaning of a casual request. Users need to know whether a statement applies once, to this project, or to the agent’s future behavior. The interface should distinguish a one-time prompt from a saved skill or routine before a person discovers the difference by accident.","A durable agent identity can help. Give it a stable name and a clear scope of work, then make its tools and memory inspectable. A face or avatar alone does not explain capability. The strongest identity is behavioral: what this agent is responsible for, which systems it can touch and what requires confirmation. Visual personality can support recognition but cannot replace the contract."),
('Reduce vocabulary without hiding risk',"Simplifying the visible concepts is good interface design if the underlying distinctions remain reachable. People should not have to learn the difference between a connector and a tool simply to ask for a summary. But they do need to understand why a document was sent to a service or why a routine ran overnight. A small number of nouns can carry the front door while a detailed activity view carries accountability.","The right disclosure is progressive. Show an accessible overview of capabilities when the agent is created. Reveal a specific permission at the moment it becomes relevant. Keep a durable record of actions, memory changes and artifacts for later review. If an agent changes its plan, announce the change rather than quietly treating an earlier approval as unlimited authority."),
('Artifacts are where value becomes inspectable',"The xAI account puts artifacts—documents, code, designs and data—on the same conceptual level as prompts and tools. That is a useful decision. A persistent agent is only as helpful as the work a person can inspect, edit and carry elsewhere. Teams should give artifacts version histories, clear ownership and links back to the task that produced them. An agent’s fluent description of a result is not a substitute for the actual file or change.","A good artifact view answers three questions: what changed, why it changed, and how a user can correct or revert it. This makes asynchronous work auditable. It also lowers dependence on the agent’s memory of its own actions. When the user comes back after a day, the product should tell the story of the work without requiring a long scroll through dialogue."),
('Routines need an expiration habit',"Scheduled prompts and reusable skills are easy to accumulate. A routine that was sensible last month may act on new data or use a tool with changed permissions. Give users a place to see active routines, their last run, next run and failure state. Ask whether a routine should expire after a fixed period or pause when it has not been reviewed. Small maintenance cues can prevent background automation from becoming invisible infrastructure.","Measure the cost of attention as well as execution. If every routine demands an approval, users may ignore them; if none does, errors may go unnoticed. Risk-based thresholds are more useful. Low-impact drafts can be batched for review. External communication, spending and destructive changes deserve a more explicit gate. The interface should communicate why the threshold exists."),
('The design lesson',"Persistent agents are a product category in which continuity and control must grow together. xAI’s five concepts are an interesting attempt to simplify the vocabulary. Other teams can borrow the method without copying its branding: decide which nouns people need to accomplish work, then design the places where complexity becomes visible at decision time.","The next empirical question is whether users can accurately predict what their agent will remember and do. Test that with real tasks over several days, not a single demo session. Ask people to point to the controls for revoking a tool, deleting a memory and recovering an artifact. If they cannot find them, a polished persistent-agent interface has not finished the job." )],
'questions':['Can a user tell whether an instruction is one-time or persistent?','Where are tools, active routines and stored memory reviewed?','Can an artifact be inspected and corrected without replaying chat?']
},
{
'slug':'atlassian-governed-agent-loops-sdlc','title':'Agent Loops Need a Review Loop of Their Own','seo':'Atlassian governed agent loops for software teams','dek':'Atlassian’s agent-loop roadmap puts context, standards and measurement around continuous software work.','category':'Engineering','image':'patterns.png','image_alt':'Software agent loop with context, code review and measurement stages','kind':'Engineering analysis','source_url':'https://www.atlassian.com/blog/jira/governed-agent-loops','source_name':'Atlassian · Governed agent loops',
'intro':"Atlassian’s September account of governed agent loops argues that software agents need shared context, controls over what they can touch and a way to measure results. Its availability notes matter: some features are in open beta, while agent loops, standards and AI review are described as private early access in the announcement. This is a roadmap and product position, not evidence that every team can deploy the whole system today. The useful design question is how a team keeps continuous agent work reviewable without reducing it to a stream of unattended pull requests.",
'sections':[
('Context is an operational dependency',"A coding agent can read a repository and still miss architectural intent. Why does one service own a piece of data? Which migration pattern is prohibited? What incident made a seemingly odd guard necessary? Those answers may live in issue discussions and experienced engineers’ memory rather than code. A shared context layer can help, but only if it points to decisions and their owners rather than dumping every document into a prompt.","Treat context as versioned product infrastructure. Give a standard a scope, date, rationale and example of correct application. Provide a route to challenge a stale rule. When an agent follows a constraint, the reviewer should be able to see which source it used. If the source is wrong, fixing the standard should improve future work more reliably than changing one prompt."),
('Autonomy requires a map of authority',"Agent loops imply repeated planning and execution. That can accelerate maintenance tasks, but the team should decide which steps are automatic, which create a draft and which need a person to approve. The permission boundary should be tied to effect: editing a test file, changing a production configuration and merging a deployment carry different consequences. One ‘agent access’ switch is too broad to explain the risk.","A workable policy distinguishes read, write, propose, merge and deploy. It names the environments and data each level can touch. Reviewers need a compact summary of actions taken since the last checkpoint and the evidence that tests actually exercised the changed behavior. Without that, continuous loops merely move the burden from creating code to understanding surprising code."),
('Measure delivered quality',"Atlassian describes measurement across throughput, quality, adoption and cost. The four dimensions are useful precisely because any one can be misleading. More commits may mean faster delivery or more rework. High adoption may reflect novelty rather than value. Lower per-task model cost may be offset by expensive reviews. Teams should measure accepted work, post-release defects and human intervention against a baseline.","Choose a narrow class of tasks, such as dependency updates or small UI fixes, and create a review rubric. Track elapsed time from issue to accepted change, number of review cycles, test failures, regressions and operational cost. Sample rejected work too. If the agent avoids hard cases, an aggregate success rate will flatter it. A credible metric describes task mix and the acceptance criteria."),
('Governance cannot be a dashboard alone',"Dashboards help leaders see patterns, but an engineer needs actionable feedback inside the workflow. Show when an agent used an outdated standard, which tool was called and which approval was bypassed or requested. Make the trace concise enough to review before merging. If every detail is in a separate analytics product, teams may learn about failure only after release.","Governance also needs an escape hatch. A rule should be overridable with a reason and a reviewer where appropriate, otherwise people will work around it. An override becomes evidence that the standard may need revision. This is a two-way relationship: policies shape agents, and observed agent failures expose weak policies."),
('The rollout question',"Before buying or building a continuous agent loop, ask what happens when the context is stale, the agent is blocked or an evaluation fails halfway. Does the system stop safely? Can a human take over with a clear state? Does the next run know which action has already occurred? These are operational questions, not visual polish. Reliability depends on explicit transitions and recovery.","Atlassian’s announcement marks an industry shift from individual prompt demos to managed execution. The idea is sound, but teams should distinguish the currently available components from early-access promises. The strongest proof will be repeatable, accepted work under visible controls, not the mere presence of agents in a Jira dashboard." )],
'questions':['What context source explains each material code decision?','Which agent actions require a reviewer before production?','How are rejected changes and regressions counted?']
},
{
'slug':'figma-prototype-to-product-decision','title':'A Clickable Prototype Is No Longer the Hard Part','seo':'Figma AI prototyping to product decisions','dek':'Figma’s September product essay puts direction and differentiation beside speed. Here is the product decision framework it suggests.','category':'Design & UX','image':'patterns.png','image_alt':'Several prototype directions converging on a tested product decision','kind':'Design analysis','source_url':'https://www.figma.com/blog/what-it-takes-to-build-great-products-now/','source_name':'Figma · What it takes to build great products now',
'intro':"In a September 24 essay, Figma’s VP of Product argues that a quick prototype does not answer whether the team picked the right direction or made something distinctive. Figma frames strong teams around speed, direction and differentiation. This is a company perspective that also promotes its workflow, not a controlled study of all product teams. The useful challenge is universal: when anyone can make a polished first draft, what evidence justifies turning that draft into a product?",
'sections':[
('The first result is a hypothesis',"A working mockup is seductive because it resolves visual ambiguity. People can click it, so they assume the concept has been tested. But a prototype may show only the chosen happy path and a small set of sample data. It says little about demand, edge cases, permissions, content quality or operational cost. Its value is to make a hypothesis discussable. The next step is not always more visual polish; often it is asking the user to complete a real task.","Teams should write the decision the prototype is meant to support. Is the risk that nobody wants the feature, that users cannot understand it, or that engineering cannot sustain it? Different risks require different evidence. A usability session, a concierge pilot and a technical spike can all be more informative than another generation of screens."),
('Compare directions before adding detail',"Fast tools make it cheaper to explore alternatives, yet teams often use the speed to refine the first plausible idea. Set aside time to make genuinely different directions: a guided flow, a direct manipulation surface, a searchable list, or an automated agent with checkpoints. Ask what each makes easy and what each hides. Comparison gives stakeholders a language for tradeoffs that a single beautiful mockup cannot provide.","Use a common task and consistent evaluation criteria across options. If one design has better sample content or receives more explanation, the comparison is biased. Record where a user hesitates, what they expect to happen and whether the system’s response matches that expectation. Direction should be selected because it solves the observed problem, not because it rendered well."),
('Differentiation is a product behavior',"A brand color and an illustration style may make a screenshot recognizable. Distinctiveness that lasts usually appears in the way a product helps someone decide, recover and finish a job. Consider an AI tool that tells users what evidence supports its answer and lets them correct a mistaken step. That behavior can be more memorable than a decorative animation because it changes whether the user trusts the result.","A team should identify its non-negotiable behavior before creating a pile of variants. What promise could a competitor not copy simply by choosing similar typography? It might be the way uncertainty is handled, the clarity of a handoff or a uniquely focused workflow. Design systems can then preserve that behavior across new screens while leaving room for expressive visual work."),
('Carry speed through the last mile',"Figma’s essay also discusses moving between direct visual edits, prompting and code. The practical insight is to choose the cheapest reliable tool for the kind of change at hand. A spacing adjustment may be faster in a property panel than in a prompt. A data-driven interaction may need code. A repeated review process can become a shared skill or plugin. Forcing every change through one interface introduces friction disguised as consistency.","The last mile includes real data, loading and error states, accessibility, performance and implementation review. A prototype that looks complete before those decisions are made can produce a dangerous feeling of closure. Put the missing states on a visible checklist and test them in a narrow slice of production code. Good handoff exposes uncertainty instead of packaging it away."),
('The decision gate',"Before promoting a prototype, ask for four artifacts: the user problem with evidence, at least one alternative direction, a test result or clearly marked untested assumption, and an implementation plan for the risky states. These are not a bureaucratic stage gate. They are a lightweight defense against the ease of making the wrong thing look finished.","AI can accelerate exploration and production when teams keep judgment explicit. The differentiator is not how quickly a mockup appeared. It is how quickly a team learned enough to choose well, and whether the shipped product still works when the ideal demo conditions disappear. That is the standard against which new design tools should be evaluated." )],
'questions':['Which user or business assumption does this prototype test?','What alternative direction was compared fairly?','Which real-data and failure states remain unproven?']
},
{
'slug':'salesforce-agent-script-deterministic-control','title':'Agent Script Exposes the Line Between Reasoning and Rules','seo':'Salesforce Agent Script: deterministic agent rules','dek':'Salesforce’s agent portfolio makes a key product distinction visible: flexible reasoning within explicit business boundaries.','category':'AI Agents','image':'agent-control-surface.png','image_alt':'A decision boundary between AI reasoning and deterministic business rules','kind':'Product analysis','source_url':'https://www.salesforce.com/ap/news/press-releases/2026/09/14/ph-salesforce-expands-agentforce-with-a-new-portfolio-of-ai-agents-built-for-high-value-work/','source_name':'Salesforce · Agentforce portfolio announcement',
'intro':"Salesforce’s September 14 Agentforce announcement describes specialized agents across service, sales, shopping and operations. It also points to Agent Script, which the company calls an open-source language for combining model reasoning with deterministic business rules. The announcement includes customer performance examples, but these are selected vendor-reported cases rather than an independent benchmark. The more useful product question is where flexible judgment ends and a rule that must always hold begins—and how a user can see that boundary when an agent acts.",
'sections':[
('Not every step should be probabilistic',"A model is useful when a customer describes an unusual problem or a seller needs to research a complex account. It is less appropriate as the sole authority for a refund ceiling, a permission check or a contractually required approval. An effective agent system can use reasoning to understand intent and choose the next step while a deterministic rule constrains the action. The exact division depends on risk, but it should be deliberate rather than an accidental prompt convention.","Think of a shopping agent that compares products, answers questions and prepares checkout. Language generation can explain a tradeoff; the price charged and inventory reserved must come from authoritative systems. A good UX shows when a suggestion is provisional and when an external transaction is about to occur. People need an opportunity to check the facts at the point of commitment."),
('Policy authors need their own interface',"If a business rule shapes agent behavior, someone must write, test and update it. That person may be a service lead or compliance owner rather than a developer. A useful rule editor should show plain-language purpose, exact conditions, example cases, owners and version history. It should warn when rules conflict or leave a gap. A natural-language summary is helpful, but the executable representation still needs review.","Changes should be evaluated on representative historical cases before they reach live customers. When a rule changes, show the expected effect: which requests would have a different outcome, what escalation volume might change and which connected systems are affected. That makes governance a product workflow instead of an emergency process after an agent makes a costly mistake."),
('Orchestration multiplies ambiguity',"Salesforce describes multi-agent orchestration across roles and systems. A task may begin in sales, cross into fulfillment and finish in support. Ownership can disappear at the seams: which agent has the current truth, who is allowed to act and what does the customer see if one participant fails? The interface should maintain one understandable task state even when several specialized agents collaborate behind the scenes.","Give each handoff an explicit input, expected output and fallback. If an agent cannot complete a step, a human should receive the history and the precise blocker. Avoid forcing the person to reconstruct a chain of bot messages. An orchestration graph is useful for operators, but the customer usually needs a simpler account: what has been completed, what is pending and whom to contact."),
('Verify outcomes, not just automation',"The announcement lists headline customer results across different products and contexts. Those figures should not be combined into an average expectation. A prospective buyer needs definitions: what counted as resolved, which channels were included, how often a human corrected the result and what the comparison period was. Vendor case studies can suggest questions; they cannot substitute for a test with your customers and policies.","Pilot one journey with a small set of permitted actions and a known escalation route. Measure incorrect action rate, customer effort, human review time and the consistency of rule application. Include exceptions and adversarial inputs. If the agent makes good suggestions but the user cannot tell when it is about to act, the product still has a control problem."),
('A clearer contract for agent products',"The promise of Agent Script is that a company can give probabilistic reasoning a stable boundary. Whether that promise works in practice depends on the quality of rules, integration and review. Product teams can use the distinction regardless of vendor: write down what must always happen, what the agent may decide, and what requires a human to confirm.","The resulting interface should not expose every implementation detail to every customer. It should reveal enough at the moment of consequence: the action proposed, the source of authority, and the path to correct an error. That is how agent flexibility can coexist with a predictable business experience." )],
'questions':['Which actions are constrained by executable rules rather than prompts?','Who reviews rule changes against real exceptions?','Can the customer distinguish a suggestion from a committed action?']
}
]
