#!/usr/bin/env python3
"""Generate, strengthen and QA the September 12, 2026 Interface Report editorial package."""
from __future__ import annotations
import base64
import hashlib
import html
import io
import pathlib
import re
import tarfile

SHA256 = "ddc1796f20a4fabf053a5e7a423da3fb3f72b32c0d3e7186abbc222692fb33b3"
repo = pathlib.Path(__file__).resolve().parents[1]
parts = [
    "editorial_payload_01.txt",
    "editorial_payload_02.txt",
    "editorial_payload_03.txt",
    "editorial_payload_04a.txt",
    "editorial_payload_04b.txt",
    "editorial_payload_05.txt",
]
payload = "".join((repo / "scripts" / name).read_text(encoding="utf-8").strip() for name in parts)
raw = base64.b64decode(payload)
actual = hashlib.sha256(raw).hexdigest()
if actual != SHA256:
    raise SystemExit(f"archive checksum mismatch: {actual}")

allowed_roots = {"analysis", "authors", "latest", "topics"}
allowed_files = {"sitemap.xml", "news-sitemap.xml", "feed.xml", "robots.txt"}
with tarfile.open(fileobj=io.BytesIO(raw), mode="r:gz") as tf:
    for member in tf.getmembers():
        if not member.isfile():
            continue
        path = pathlib.PurePosixPath(member.name)
        if path.is_absolute() or ".." in path.parts:
            raise SystemExit(f"unsafe archive path: {member.name}")
        if path.parts[0] not in allowed_roots and member.name not in allowed_files:
            raise SystemExit(f"unexpected output path: {member.name}")
        source = tf.extractfile(member)
        if source is None:
            continue
        target = repo.joinpath(*path.parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(source.read())

SEO_TITLES = {
    "data-agent-kills-dashboard-first-analytics": "AI Analytics UX: Data Agents vs Dashboards | Interface Report",
    "gpt-6-astra-model-is-not-the-product": "GPT-6 Astra: Why the Model Is Not the Product | Interface Report",
    "agents-api-build-vs-orchestrate": "Agents API: Build vs Orchestrate AI Agents | Interface Report",
    "agent-harness-portability-infrastructure": "Agent Harness Portability Is Infrastructure | Interface Report",
    "permission-ux-is-ai-safety-interface": "Permission UX Is the AI Safety Interface | Interface Report",
    "evidence-loop-ai-analytics-trust": "AI Analytics Trust: Build the Evidence Loop | Interface Report",
    "full-duplex-voice-ui-design-rules": "Full-Duplex Voice UI: New Design Rules | Interface Report",
    "stop-making-every-ai-feature-chat": "Stop Making Every AI Feature a Chat Box | Interface Report",
    "production-agent-sandbox-checklist": "Production Agent Sandbox Checklist | Interface Report",
    "tail-latency-ai-product-engineering": "Tail Latency Is Where AI Products Break | Interface Report",
    "ai-pricing-is-a-product-system": "AI Pricing Is a Product System | Interface Report",
    "agent-ready-saas-nonhuman-buyer": "Agent-Ready SaaS: Design for AI Buyers | Interface Report",
}

SEO_DESCRIPTIONS = {
    "ai-pricing-is-a-product-system": "AI pricing is shifting from static tiers to usage, outcomes and controls. See how SaaS teams can design pricing as part of the product.",
    "agent-ready-saas-nonhuman-buyer": "AI agents are becoming software buyers and operators. SaaS teams need machine-readable capabilities, clear permissions and reliable APIs.",
}

EXPANSIONS = {
"data-agent-kills-dashboard-first-analytics": """<h2>The dashboard becomes a saved state, not the starting point</h2><p>The practical consequence is organizational as much as visual. Today, analysts spend a surprising amount of time maintaining dashboards whose main job is to answer questions that recur often enough to deserve a permanent view. A data agent changes that economics. Teams can reserve persistent dashboards for operational signals that truly require continuous monitoring, while exploratory questions move into an evidence-backed conversational workflow. That reduces dashboard sprawl, but it also raises the bar for what earns permanent screen real estate. A chart should persist because a team needs shared situational awareness, not simply because someone once asked for it.</p><p>Design teams should also rethink history and shareability. A useful agent session should be reproducible: another person needs to see the question, scope, assumptions, data sources, transformations and resulting visualization without reconstructing the conversation from screenshots. Saved analytical threads can become lightweight decision records. That gives product managers, finance teams and operators a better artifact than a static dashboard link because the reasoning path travels with the answer. The core UX requirement is therefore not “make chat fast.” It is “make the analysis inspectable, repeatable and safe to hand off.” Products that solve that layer can replace a large amount of informal spreadsheet and Slack analysis without asking users to trust a black box.</p>""",
"gpt-6-astra-model-is-not-the-product": """<h2>Capability gains compress feature advantages quickly</h2><p>A stronger foundation model can make a demo look dramatically better overnight, but it can also erase the differentiation of products that were built around yesterday’s model limitation. If a feature is valuable only because the base model could not previously perform a task, its moat is temporary by definition. Durable AI products push differentiation outward: proprietary workflow context, high-quality interaction design, distribution, trusted data access, evaluation systems, permissions and the ability to complete work across real tools. Those layers remain difficult even when raw model intelligence improves.</p><p>This is why model upgrades should be treated as a product architecture event rather than a marketing event. Teams need regression suites that compare not only benchmark quality but also tone, latency, tool selection, refusal behavior, cost and edge-case reliability. A model that is objectively more capable can still make a specific workflow worse if it changes the timing or shape of the interaction. The best teams maintain a capability boundary: they know exactly which behaviors they delegate to the model and which behaviors remain constrained by deterministic product logic. That boundary lets them adopt new models quickly without letting every model release redefine the product. In practice, the winning question is not “which model is smartest?” It is “which parts of the user promise should remain stable regardless of the model underneath?”</p>""",
"agents-api-build-vs-orchestrate": """<h2>The architecture decision moves up one level</h2><p>When an agent platform provides sessions, tools, state, tracing and managed execution, teams no longer have to decide only whether to build an agent. They must decide which orchestration responsibilities are strategic enough to own. A support workflow may benefit from a managed runtime because reliability and speed to market matter more than custom planning logic. A regulated approval workflow may need tighter control over every tool call, state transition and evidence record. The useful build-versus-buy comparison is therefore granular: identity, memory, tool routing, sandboxing, observability, evaluation and human approval can each have a different ownership decision.</p><p>That decomposition also makes migration less painful. If application code treats the agent runtime as one replaceable layer, teams can test another provider or an internal harness without rewriting the product shell. Stable contracts matter: tool schemas, event formats, state objects and permission decisions should be explicit at the boundary. This is especially important for startups because early convenience can become late lock-in. The fastest architecture is not necessarily the one with the fewest components; it is the one that keeps irreversible decisions small. Managed orchestration is most valuable when it removes undifferentiated infrastructure while preserving an escape hatch for the workflows that eventually become core intellectual property.</p>""",
"agent-harness-portability-infrastructure": """<h2>Portability starts with events, not provider names</h2><p>Most agent stacks expose roughly the same conceptual ingredients—messages, tool calls, tool results, state and completion—but they encode them differently. Teams that normalize those events inside their own product gain leverage. The UI can render a stable progress model while the underlying harness changes. Evaluation infrastructure can compare runs across providers. Analytics can answer operational questions without knowing whether a trace came from an internal loop, an SDK or a hosted agent service. That normalization layer looks like plumbing, but it becomes strategic the moment a team needs to move a high-value workflow.</p><p>Portability also improves incident response. If an agent provider has a reliability problem, a clean harness boundary makes fallback realistic instead of theoretical. The goal is not multi-provider complexity for its own sake; it is avoiding accidental coupling between product behavior and one vendor’s private event model. Teams should define their own minimal contract for tool invocation, approvals, artifacts, errors and trace IDs, then write adapters around it. The narrower that contract is, the easier it becomes to add specialized runtimes for coding, research, browser work or enterprise data without fragmenting the interface. In that sense, harness portability is becoming similar to observability or authentication: invisible when it works, expensive to retrofit after the product has scaled.</p>""",
"permission-ux-is-ai-safety-interface": """<h2>Good permission design makes autonomy legible</h2><p>Users do not experience an agent’s safety policy as a policy document. They experience it at the exact moment the system asks to read a file, send a message, spend money, modify data or act on another service. That makes permission UX one of the highest-leverage safety surfaces in the product. A vague confirmation such as “Allow?” forces the user to infer scope. A strong confirmation names the action, target, consequence, duration and whether the permission can be reused. The difference is not cosmetic: it determines whether consent is informed.</p><p>Products should also separate low-risk continuity from high-risk escalation. Requiring approval for every harmless read destroys usability and trains people to click through prompts. Granting broad standing access for consequential writes creates the opposite problem. Risk-tiered permissions give teams a better middle ground: reads can be scoped to a session or dataset, while sending, deleting, purchasing or publishing can require explicit confirmation at the moment of action. The interface should preserve a visible audit trail so users can answer “what did the agent do under my authority?” after the fact. As agents become more capable, that record becomes part of trust itself. Safety is not only preventing bad actions; it is ensuring the human can understand, constrain and review the authority delegated to the system.</p>""",
"evidence-loop-ai-analytics-trust": """<h2>Trust is built through reversible inspection</h2><p>AI analytics is most credible when the user can move backward from a conclusion to the evidence without leaving the task. That means citations should not be decorative footnotes. A user should be able to open the source, see the relevant row or passage, inspect filters and understand how an intermediate calculation was derived. When a number looks wrong, the product needs to support correction rather than forcing a new conversation from zero. Reversibility turns trust from a vague feeling into an interaction the user can perform.</p><p>The second requirement is to distinguish confidence from authority. A model may sound certain even when the underlying dataset is incomplete, delayed or ambiguously defined. The interface can expose those conditions directly: freshness, coverage, missing values, metric definition and scope belong near the claim. This is particularly important when an answer leads directly to an action such as changing budget, contacting customers or adjusting inventory. The product should make the evidence checkpoint visible before commitment. Over time, teams can measure which claims are inspected, challenged or corrected and use that behavior as evaluation data. The evidence loop therefore improves both user trust and model quality: every challenge is a signal about where the system’s reasoning or data contract needs to become more explicit.</p>""",
"full-duplex-voice-ui-design-rules": """<h2>Voice needs an interruption model, not just a waveform</h2><p>Full-duplex systems can listen while speaking, which makes the interaction feel more natural but also removes the clean turn boundary that older voice interfaces relied on. The product must decide what happens when the user says “wait,” corrects a name, starts a new thought or makes a background noise while the assistant is talking. Those moments need deterministic interaction rules. The user should be able to interrupt immediately, understand whether the previous response was canceled or paused, and recover context without repeating the entire request.</p><p>Visual state still matters even in a voice-first experience. A compact display of listening, thinking, speaking and acting states helps users understand whether the system heard them and whether an external action is underway. High-risk actions should never disappear into conversational flow; sending, buying, deleting or publishing needs a clear confirmation surface that survives audio ambiguity. Designers should also test latency distribution rather than only average latency, because a voice interaction that feels instant nine times and stalls on the tenth quickly becomes unpredictable. The best full-duplex interface is not the one that imitates human conversation most aggressively. It is the one that combines conversational fluidity with machine-level clarity about state, interruption and consequence.</p>""",
"stop-making-every-ai-feature-chat": """<h2>Match the interface to the shape of the task</h2><p>Chat is excellent when intent is ambiguous, the path is exploratory or the user benefits from progressive refinement. It is weak when the task is repetitive, parameter-heavy or needs comparison across several options. A pricing configuration, design token edit or deployment approval often works better as structured controls with AI embedded behind them. The model can recommend values, explain trade-offs and generate defaults without forcing the user to express every change in prose. The result is faster, more scannable and easier to verify.</p><p>A useful design test is to ask what information the user needs to compare at one glance. If the answer includes rows, states, permissions, versions or before-and-after differences, a persistent structured surface usually beats a scrolling conversation. Chat can remain as an escape hatch for exceptions. This hybrid approach also improves accessibility and reliability because deterministic controls carry the final state while language handles intent. The goal is not to minimize chat; it is to stop treating chat as the product identity of AI. Mature AI interfaces will feel less like a chatbot attached to software and more like software whose existing controls become smarter, more adaptive and more capable of explaining themselves.</p>""",
"production-agent-sandbox-checklist": """<h2>Isolation is only the first containment boundary</h2><p>A sandbox can stop an agent from directly touching the host system, but production safety depends on everything the sandbox can still reach. Network egress, temporary credentials, mounted files, package installation and artifact export each create a separate path for damage or data leakage. Teams should define those paths explicitly. Default-deny networking, short-lived scoped credentials and disposable workspaces are more useful than a broad “sandboxed” label because they describe the actual authority available during a run.</p><p>Operational controls matter just as much. Every run should have a hard time limit, resource ceiling, trace identifier and a way to terminate execution immediately. Logs need enough detail to reconstruct tool calls without accidentally storing secrets. Artifacts should pass through validation before they leave the sandbox, especially when code or documents can be executed elsewhere. The most reliable design also assumes the model will eventually behave unexpectedly. That means containment has to remain effective even when the agent chooses the wrong command, follows a malicious instruction in retrieved content or loops indefinitely. Production readiness is therefore a systems property: isolation, credentials, networking, observability and human escalation all have to fail safely together.</p>""",
"tail-latency-ai-product-engineering": """<h2>Design for p95, not the demo</h2><p>Teams often optimize AI experiences around a fast median response because that is what a happy-path demo shows. Users, however, remember the outliers. A tool call that occasionally waits ten seconds, a retrieval step that stalls or a model response that streams slowly can make the whole product feel unreliable even when average latency is excellent. Engineering teams should therefore track p50, p95 and p99 across the entire interaction chain, not just the model API. Each external dependency needs its own budget and timeout.</p><p>The interface should be built around those distributions too. Progressive results, cancellable work, visible sub-steps and sensible fallback states make long-tail events survivable. If the agent can continue useful work while one dependency is slow, expose that progress instead of freezing the screen. If a slow tool is optional, skip it and explain the degraded result. Caching stable context and precomputing expensive metadata can remove latency before the model is even called. The broader point is that speed is not one metric; it is a reliability contract. Products feel fast when users know what is happening and can keep control during the slowest realistic cases, not only when a benchmark reports a low average.</p>""",
"ai-pricing-is-a-product-system": """<h2>Pricing logic now has to live inside the experience</h2><p>AI products create variable cost in ways that classic seat-based SaaS did not. One user can trigger a lightweight classification while another launches a long research run with tools, retrieval and large context. Hiding that variability until the invoice arrives creates distrust. The product should show the unit that matters—credits, tasks, successful outcomes, compute time or another understandable measure—close to the action that consumes it. Users need a way to predict cost before they scale a workflow.</p><p>That makes limits and controls part of product design. Teams can offer budgets, alerts, per-workspace caps and clear explanations of what increases usage. Enterprise buyers may also need policy controls that prevent an agent from selecting a more expensive path without approval. Pricing experiments should therefore measure more than conversion on the public pricing page. They should track whether customers understand the meter, whether usage feels proportional to value and where cost anxiety causes abandonment. The strongest pricing system aligns the billable unit with the job the customer believes was completed. When that alignment is clear, monetization feels like part of the workflow rather than a tax imposed after it.</p>""",
"agent-ready-saas-nonhuman-buyer": """<h2>Agents need a product surface they can parse and trust</h2><p>If software agents are going to discover, evaluate and operate SaaS products, marketing copy alone will not be enough. Capabilities need machine-readable descriptions, stable APIs and explicit schemas. An agent should be able to determine what an action does, which inputs are required, what it costs, what permissions it needs and what errors can occur. Human documentation remains important, but the operational contract must be precise enough for software to reason over without guessing.</p><p>Identity and authority are equally important. A nonhuman operator still acts on behalf of a person or organization, so products need delegated credentials, scoped permissions and auditability. Rate limits should communicate recovery behavior, and destructive actions should expose confirmation or policy hooks rather than assuming a human is watching every request. Commercial models may change as well: an agent can compare vendors continuously, route work dynamically and optimize for price or reliability. SaaS teams that make their product easy to evaluate programmatically can become preferred infrastructure in those automated purchasing loops. “Agent-ready” therefore means more than having an API. It means making capability, trust, cost and control legible to both machines and the humans who authorize them.</p>""",
}

for slug, extra in EXPANSIONS.items():
    p = repo / "analysis" / slug / "index.html"
    text = p.read_text(encoding="utf-8")
    marker = "<h2>Practical takeaways</h2>"
    if extra not in text:
        if marker not in text:
            raise SystemExit(f"missing practical takeaways marker in {slug}")
        text = text.replace(marker, extra + "\n" + marker, 1)
    title = SEO_TITLES[slug]
    text = re.sub(r"<title>.*?</title>", f"<title>{html.escape(title)}</title>", text, count=1, flags=re.S)
    text = re.sub(r'(<meta property="og:title" content=")[^"]*("/>)', rf'\1{html.escape(title, quote=True)}\2', text, count=1)
    text = re.sub(r'(<meta name="twitter:title" content=")[^"]*("/>)', rf'\1{html.escape(title, quote=True)}\2', text, count=1)
    if slug in SEO_DESCRIPTIONS:
        desc = SEO_DESCRIPTIONS[slug]
        text = re.sub(r'(<meta name="description" content=")[^"]*("/>)', rf'\1{html.escape(desc, quote=True)}\2', text, count=1)
        text = re.sub(r'(<meta property="og:description" content=")[^"]*("/>)', rf'\1{html.escape(desc, quote=True)}\2', text, count=1)
        text = re.sub(r'(<meta name="twitter:description" content=")[^"]*("/>)', rf'\1{html.escape(desc, quote=True)}\2', text, count=1)
    article_match = re.search(r'<article class="prose">(.*?)</article>', text, flags=re.S)
    if not article_match:
        raise SystemExit(f"missing prose article in {slug}")
    plain = re.sub(r"<[^>]+>", " ", article_match.group(1))
    word_count = len(html.unescape(plain).split())
    text = re.sub(r'"wordCount":\d+', f'"wordCount":{word_count}', text, count=1)
    p.write_text(text, encoding="utf-8")
    print(f"strengthened {slug}: {word_count} words")

not_found = repo / "404.html"
text404 = not_found.read_text(encoding="utf-8")
if 'property="og:locale"' not in text404:
    text404 = text404.replace('<meta property="og:site_name" content="Interface Report"/>', '<meta property="og:site_name" content="Interface Report"/><meta property="og:locale" content="en_US"/>', 1)
    not_found.write_text(text404, encoding="utf-8")
    print("added og:locale to 404.html")
